# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=20)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('available', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=0)),
                ('brand', models.CharField(choices=[('WHISKY', 'whisky'), ('BEER', 'beer')], default='whisky', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
