# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-01 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20170826_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='place',
            new_name='latlng',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='road',
            new_name='name',
        ),
        migrations.AddField(
            model_name='address',
            name='place_address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='place_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
