# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20170901_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-created',)},
        ),
    ]
