# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clear',
            field=models.BooleanField(default=False),
        ),
    ]
