# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DRINKS', 'drinks'), ('VEGETABLES', 'vegetables')], default='drinks', max_length=100),
        ),
    ]
