# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170502_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='cat_type',
            new_name='type',
        ),
    ]
