# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170502_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='active',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='type',
            field=models.CharField(choices=[('DRINK', 'drink'), ('VEGETABLE', 'vegetable')], default='drink', max_length=100),
        ),
    ]
