# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170502_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default='/static/images/default.jpg', upload_to='products'),
        ),
    ]
