# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/images/default.png', upload_to='products'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default='/images/default.png', upload_to='categories'),
        ),
    ]
