# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170512_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
