# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20170826_0601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('created',)},
        ),
    ]
